import { User } from './User';
import { Event } from './Event';
import { Product } from './Product';
import { Identifier } from './Identifier';
import { Gender } from './Gender';
import { CallbackType } from './CallbackType';
import { ContentOptimizerDataType } from './ContentOptimizerDataType';
import { InsiderAppCards } from './InsiderAppCards';
import { InsiderAppCardsError, InsiderAppCardsErrorCode } from './InsiderAppCardsError';
import { CloseButtonPosition } from './CloseButtonPosition';

export type CustomParameters = {
    [key: string]: string | number | boolean | Date | number[] | string[];
};

interface InsiderPlugin {
    init(partnerName: string, appGroup: string, handleNotificationCallback: Function): void;
    initWithCustomEndpoint(partnerName: string, appGroup: string, endpoint: string, handleNotificationCallback: Function): void;
    reinitWithPartnerName(partnerName: string): void;
    tagEvent(eventName: string): Event;
    getCurrentUser(): User;
    createNewProduct(productID: string, name: string, taxonomy: Array<string>, imageURL: string, price: number, currency: string): Product;
    itemPurchased(uniqueSaleID: string, product: Product, customParameters?: CustomParameters): void;
    itemAddedToCart(product: Product, customParameters?: CustomParameters): void;
    itemRemovedFromCart(productID: string): void;
    itemRemovedFromCart(productID: string, customParameters: CustomParameters): void;
    itemRemovedFromCart(productID: string, saleID: string): void;
    itemRemovedFromCart(productID: string, saleID: string, customParameters: CustomParameters): void;
    cartCleared(customParameters?: CustomParameters): void;
    itemAddedToWishlist(product: Product, customParameters?: CustomParameters): void;
    itemRemovedFromWishlist(productID: string, customParameters?: CustomParameters): void;
    wishlistCleared(customParameters?: CustomParameters): void;
    visitWishlistPage(products: Array<Product>, customParameters?: CustomParameters): void;
    getMessageCenterData(limit: number, startDate: Date, endDate: Date): Promise<any>;
    getMessageCenterDataWithIdentifiers(limit: number, startDate: Date, endDate: Date, identifiers: object): Promise<any>;
    getSmartRecommendation(recommendationID: number, locale: string, currency: string): Promise<any>;
    getSmartRecommendationWithProduct(product: Product, recommendationID: number, locale: string): Promise<any>;
    getSmartRecommendationWithProductIDs(productIDs: Array<string>, recommendationID: number, locale: string, currency: string): Promise<any>;
    clickSmartRecommendationProduct(product: Product, recommendationID: number): void;
    getContentStringWithName(variableName: string, defaultValue: string, contentOptimizerDataType: number): Promise<any>;
    getContentBoolWithName(variableName: string, defaultValue: boolean, contentOptimizerDataType: number): Promise<any>;
    getContentIntWithName(variableName: string, defaultValue: number, contentOptimizerDataType: number): Promise<any>;
    getContentStringWithoutCache(variableName: string, defaultValue: string, contentOptimizerDataType: number): Promise<any>;
    getContentBoolWithoutCache(variableName: string, defaultValue: boolean, contentOptimizerDataType: number): Promise<any>;
    getContentIntWithoutCache(variableName: string, defaultValue: number, contentOptimizerDataType: number): Promise<any>;
    visitHomePage(customParameters?: CustomParameters): void;
    visitListingPage(taxonomy: Array<string>, customParameters?: CustomParameters): void;
    visitProductDetailPage(product: Product, customParameters?: CustomParameters): void;
    visitCartPage(products: Array<Product>): void;
    visitCartPage(products: Array<Product>, customParameters: CustomParameters): void;
    visitCartPage(products: Array<Product>, saleID: string): void;
    visitCartPage(products: Array<Product>, saleID: string, customParameters: CustomParameters): void;
    startTrackingGeofence(): void;
    setGDPRConsent(gdprConsent: boolean): void;
    setMobileAppAccess(mobileAppAccess: boolean): void;
    enableIDFACollection(idfaCollection: boolean): void;
    removeInapp(): void;
    registerWithQuietPermission(booleanValue: boolean): void;
    setPushToken(token: string): void;
    enableLocationCollection(locationCollection: boolean): void;
    enableIpCollection(ipCollection: boolean): void;
    enableCarrierCollection(carrierCollection: boolean): void;
    signUpConfirmation(customParameters?: CustomParameters): void;
    setActiveForegroundPushView(): void;
    setInternalBrowserCloseButtonPosition(position: string): void;
    setForegroundPushCallback(callback: Function): void;
    handleNotification(userInfo: object): void;
    getInsiderID(): Promise<string>;
    registerInsiderIDListener(insiderIDCallback: (insiderID: string) => void): void;
    disableInAppMessages(): void;
    enableInAppMessages(): void;
    showNativeAppReview(): void;
    handleUniversalLink(url: string): void;
    handleURL(url: string): void;

    gender: Gender;
    callbackType: CallbackType;
    contentOptimizerDataType: ContentOptimizerDataType;
    closeButtonPosition: CloseButtonPosition;
    identifier(): Identifier;
    appCards: InsiderAppCards;
    AppCardsError: typeof InsiderAppCardsError;
    AppCardsErrorCode: typeof InsiderAppCardsErrorCode;
}

declare const Insider: InsiderPlugin;
export default Insider;
